### ISSUE TITLE
Add Readme.md For Chinese

### ISSUE THREAD

**Issue by lispking** [project-robius/.github#1]
Recently, I got to know about Robius at the GOSIM WORKSHOP. As a beginner in Rust, I hope to contribute to the Robius project. This morning, I translated my boss's article, please take a look, thank you.

Chinese Version: https://lispking.github.io/2023/10/15/rust-robius-project-update/

**Comment by kevinaboos** [comment]
Hi @lispking, thanks for the translation, that would indeed be very useful to have since we have a fair number of Chinese-speaking folks on the team, and we'd also like all the materials to be inclusive of Chinese language speakers (and other languages too)!

Just to clarify, is this your translation, or a translation using AI, or a combination of both? I'd just like to know for proper attribution reasons.

This looks good to me so far (my Chinese ability is pretty elementary though), but we can certainly have other native speakers review it too. Would you be interested in submitting this as a PR such that we can include it in the main repo? If so, I'd recommend putting it in a file called `README_ZH_CN.md` and then linking to that from the main README.md such that others can discover it (i can add the latter part later).

**Comment by lispking** [comment]
Thank you for @kevinaboos 's reply. This is a translation from a combination of AI and personal secondary checks. I am also very interested in Rust and currently a freelancer. I hope to make some contributions to the community.

**Comment by kevinaboos** [comment]
Thanks! 

Closed by #2.

**Comment by kevinaboos** [comment]
Thanks! 

Closed by #2.
